//
//  ServiceMock.swift
//  MovieDBTests
//
//  Created by Gabriel Ferreira on 01/09/20.
//  Copyright © 2020 Ribeiro Ferreira. All rights reserved.
//

import Foundation
@testable import MovieDB

class ServiceMock : ServiceProtocol {
    let listResponse : [String : Any] = [
       "results":[
          [
             "popularity":1196.276,
             "vote_count":108,
             "video":false,
             "poster_path":"uOw5JD8IlD546feZ6oxbIjvN66P.jpg",
             "id":718444,
             "adult":false,
             "backdrop_path":"x4UkhIQuHIJyeeOTdcbZ3t3gBSa.jpg",
             "original_language":"en",
             "original_title":"Rogue",
             "genre_ids":[
                28
             ],
             "title":"Rogue",
             "vote_average":6,
             "overview":"",
             "release_date":"2020-08-20"
          ],
          [
             "popularity":713.471,
             "vote_count":160,
             "video":false,
             "poster_path":"uGhQ2ZGBpzCj6wC5jUrybsZuPTI.jpg",
             "id":539885,
             "adult":false,
             "backdrop_path":"ekkuqt9Q2ad1F7xq2ZONP0oq36P.jpg",
             "original_language":"en",
             "original_title":"Ava",
             "genre_ids":[
                28,
                80,
                18,
                53
             ],
             "title":"Ava",
             "vote_average":6.3,
             "overview":"",
             "release_date":"2020-08-06"
          ],
          [
             "popularity":352.006,
             "vote_count":741,
             "video":false,
             "poster_path":"k68nPLbIST6NP96JmTxmZijEvCA.jpg",
             "id":577922,
             "adult":false,
             "backdrop_path":"wzJRB4MKi3yK138bJyuL9nx47y6.jpg",
             "original_language":"en",
             "original_title":"Tenet",
             "genre_ids":[
                28,
                878,
                53
             ],
             "title":"Tenet",
             "vote_average":7.5,
             "overview":"",
             "release_date":"2020-08-22"
          ],
          [
             "popularity":352.674,
             "vote_count":253,
             "video":false,
             "poster_path":"ew1lAU8yV66JbivBU1Zh4Wj4pOB.jpg",
             "id":581392,
             "adult":false,
             "backdrop_path":"gEjNlhZhyHeto6Fy5wWy5Uk3A9D.jpg",
             "original_language":"ko",
             "original_title":"반도",
             "genre_ids":[
                28,
                27,
                53
             ],
             "title":"반도",
             "vote_average":7.4,
             "overview":"",
             "release_date":"2020-07-15"
          ],
          [
             "popularity":478.848,
             "vote_count":54,
             "video":false,
             "poster_path":"5pe30v0z4ucVgwh5nR439cCzwwO.jpg",
             "id":632618,
             "adult":false,
             "backdrop_path":"cVdYaAQmd5DZNdo0KFJruz7JpUs.jpg",
             "original_language":"es",
             "original_title":"Crímenes de familia",
             "genre_ids":[
                80,
                18,
                53
             ],
             "title":"Crímenes de familia",
             "vote_average":7,
             "overview":"",
             "release_date":"2020-08-20"
          ],
          [
             "popularity":410.708,
             "vote_count":522,
             "video":false,
             "poster_path":"zG2l9Svw4PTldWJAzC171Y3d6G8.jpg",
             "id":385103,
             "adult":false,
             "backdrop_path":"fKtYXUhX5fxMxzQfyUcQW9Shik6.jpg",
             "original_language":"en",
             "original_title":"Scoob!",
             "genre_ids":[
                12,
                16,
                35,
                10751
             ],
             "title":"Scoob!",
             "vote_average":7.4,
             "overview":"",
             "release_date":"2020-07-08"
          ],
          [
             "popularity":321.742,
             "vote_count":108,
             "video":false,
             "poster_path":"3eg0kGC2Xh0vhydJHO37Sp4cmMt.jpg",
             "id":531499,
             "adult":false,
             "backdrop_path":"zogWnCSztU8xvabaepQnAwsOtOt.jpg",
             "original_language":"en",
             "original_title":"The Tax Collector",
             "genre_ids":[
                28,
                80,
                18
             ],
             "title":"The Tax Collector",
             "vote_average":6,
             "overview":"",
             "release_date":"2020-08-07"
          ],
          [
             "popularity":228.864,
             "vote_count":58,
             "video":false,
             "poster_path":"4V2nTPfeB59TcqJcUfQ9ziTi7VN.jpg",
             "id":501979,
             "adult":false,
             "backdrop_path":"oazPqs1z78LcIOFslbKtJLGlueo.jpg",
             "original_language":"en",
             "original_title":"Bill & Ted Face the Music",
             "genre_ids":[
                12,
                35,
                878
             ],
             "title":"Bill & Ted Face the Music",
             "vote_average":6.5,
             "overview":"",
             "release_date":"2020-08-27"
          ],
          [
             "popularity":198.463,
             "vote_count":5512,
             "video":false,
             "poster_path":"aQvJ5WPzZgYVDrxLX4R6cLJCEaQ.jpg",
             "id":454626,
             "adult":false,
             "backdrop_path":"stmYfCUGd8Iy6kAMBr6AmWqx8Bq.jpg",
             "original_language":"en",
             "original_title":"Sonic the Hedgehog",
             "genre_ids":[
                28,
                35,
                878,
                10751
             ],
             "title":"Sonic the Hedgehog",
             "vote_average":7.5,
             "overview":"",
             "release_date":"2020-02-12"
          ],
          [
             "popularity":189.762,
             "vote_count":8982,
             "video":false,
             "poster_path":"eJ0kCMcqKLBUaHhB9PfOMFu2uim.jpg",
             "id":496243,
             "adult":false,
             "backdrop_path":"ApiBzeaa95TNYliSbQ8pJv4Fje7.jpg",
             "original_language":"ko",
             "original_title":"기생충",
             "genre_ids":[
                35,
                18,
                53
             ],
             "title":"기생충",
             "vote_average":8.5,
             "overview":"",
             "release_date":"2019-05-30"
          ],
          [
             "popularity":186.974,
             "vote_count":47,
             "video":false,
             "poster_path":"dKjD3DTZjRI3Ipkf7Oz5zAILnwD.jpg",
             "id":659991,
             "adult":false,
             "backdrop_path":"5nRyaVklxyA9OkxqZaPv1KBRqpd.jpg",
             "original_language":"en",
             "original_title":"Made in Italy",
             "genre_ids":[
                35,
                18
             ],
             "title":"Made in Italy",
             "vote_average":6,
             "overview":"",
             "release_date":"2020-08-06"
          ],
          [
             "popularity":185.754,
             "vote_count":2981,
             "video":false,
             "poster_path":"3VqDLgKLfNYSQYEGC5sjGhcPhn7.jpg",
             "id":508439,
             "adult":false,
             "backdrop_path":"xFxk4vnirOtUxpOEWgA1MCRfy6J.jpg",
             "original_language":"en",
             "original_title":"Onward",
             "genre_ids":[
                12,
                16,
                35,
                14,
                10751
             ],
             "title":"Onward",
             "vote_average":7.9,
             "overview":"",
             "release_date":"2020-02-29"
          ],
          [
             "popularity":178.061,
             "vote_count":6285,
             "video":false,
             "poster_path":"AuGiPiGMYMkSosOJ3BQjDEAiwtO.jpg",
             "id":530915,
             "adult":false,
             "backdrop_path":"cqa3sa4c4jevgnEJwq3CMF8UfTG.jpg",
             "original_language":"en",
             "original_title":"1917",
             "genre_ids":[
                28,
                18,
                36,
                10752
             ],
             "title":"1917",
             "vote_average":7.9,
             "overview":"",
             "release_date":"2019-12-25"
          ],
          [
             "popularity":232.705,
             "vote_count":10,
             "video":false,
             "poster_path":"oB3LX9C3FbJvPtrk1J7qHQKvzLr.jpg",
             "id":623958,
             "adult":false,
             "backdrop_path":"gQa5l8NrPHQzoqLeideAzuPMZQj.jpg",
             "original_language":"en",
             "original_title":"The Bay of Silence",
             "genre_ids":[
                53
             ],
             "title":"The Bay of Silence",
             "vote_average":4.2,
             "overview":"",
             "release_date":"2020-08-20"
          ],
          [
             "popularity":164.382,
             "vote_count":75,
             "video":false,
             "poster_path":"xZNw9xxtwbEf25NYoz52KdbXHPM.jpg",
             "id":340102,
             "adult":false,
             "backdrop_path":"2AFZyra0Ddwl2oBDhClvD1qSIL6.jpg",
             "original_language":"en",
             "original_title":"The New Mutants",
             "genre_ids":[
                28,
                12,
                27,
                878
             ],
             "title":"The New Mutants",
             "vote_average":5.8,
             "overview":"",
             "release_date":"2020-08-26"
          ],
          [
             "popularity":161.842,
             "vote_count":312,
             "video":false,
             "poster_path":"hPkqY2EMqWUnFEoedukilIUieVG.jpg",
             "id":531876,
             "adult":false,
             "backdrop_path":"n1RohH2VoK1CdVI2fXvcP19dSlm.jpg",
             "original_language":"en",
             "original_title":"The Outpost",
             "genre_ids":[
                28,
                18,
                36,
                10752
             ],
             "title":"The Outpost",
             "vote_average":6.7,
             "overview":"",
             "release_date":"2020-06-24"
          ],
          [
             "popularity":138.055,
             "vote_count":1075,
             "video":false,
             "poster_path":"7W0G3YECgDAfnuiHG91r8WqgIOe.jpg",
             "id":446893,
             "adult":false,
             "backdrop_path":"qsxhnirlp7y4Ae9bd11oYJSX59j.jpg",
             "original_language":"en",
             "original_title":"Trolls World Tour",
             "genre_ids":[
                12,
                16,
                35,
                14,
                10402,
                10751
             ],
             "title":"Trolls World Tour",
             "vote_average":7.6,
             "overview":"",
             "release_date":"2020-03-12"
          ],
          [
             "popularity":165.19,
             "vote_count":36,
             "video":false,
             "poster_path":"eDnHgozW8vfOaLHzfpHluf1GZCW.jpg",
             "id":606234,
             "adult":false,
             "backdrop_path":"u9YEh2xVAPVTKoaMNlB5tH6pXkm.jpg",
             "original_language":"en",
             "original_title":"Archive",
             "genre_ids":[
                878
             ],
             "title":"Archive",
             "vote_average":6.6,
             "overview":"",
             "release_date":"2020-08-13"
          ],
          [
             "popularity":148.87,
             "vote_count":36,
             "video":false,
             "poster_path":"zGqWBK9hrpXRnhgoey8flcSb3Ma.jpg",
             "id":633604,
             "adult":false,
             "backdrop_path":"mFofjESo9brnQYdIq8r42nFLvSe.jpg",
             "original_language":"nl",
             "original_title":"Yummy",
             "genre_ids":[
                28,
                35,
                27
             ],
             "title":"Yummy",
             "vote_average":7.3,
             "overview":"",
             "release_date":"2020-07-23"
          ],
          [
             "popularity":160.626,
             "vote_count":54,
             "video":false,
             "poster_path":"dxFqZiO5MqqVoFZuWOjTdjmDh6d.jpg",
             "id":315064,
             "adult":false,
             "backdrop_path":"q5uZqd324Tug2xWxL72j18ZzK2Z.jpg",
             "original_language":"en",
             "original_title":"Animal Crackers",
             "genre_ids":[
                12,
                16,
                35
             ],
             "title":"Animal Crackers",
             "vote_average":6.9,
             "overview":"",
             "release_date":"2020-07-30"
          ]
       ],
       "page":1,
       "total_results":878,
       "dates":[
          "maximum":"2020-08-30",
          "minimum":"2020-07-13"
       ],
       "total_pages":44
    ]
    
    func getData(from url: String, parameters: [String:Any]?, callBack: @escaping CallBack) throws {
        do {
            let jsonData = try JSONSerialization.data(withJSONObject: self.listResponse, options: [])
            
            callBack(jsonData, true, "")
        } catch {
            print(error)
        }
    }
}

